apiVersion: apps/v1
kind: Deployment

metadata:
  name: user-service-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      app: user-service

  template:
    metadata:
      labels:
        app: user-service

    spec:
      containers:
        - name: user-service

          image: user-service:latest
          imagePullPolicy: Never

          ports:
            - containerPort: 8081

          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://registry-service:8761/eureka

            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://host.docker.internal:3306/user_db

            - name: SPRING_DATASOURCE_USERNAME
              value: root

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: banking-secret
                  key: DB_PASSWORD